/* ========================================================================
 * Copyright 2014 Escher96
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Escher96

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.Escher96.obra.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.Escher96.obra.logic.dto.ObraPageDTO;
import co.edu.uniandes.csw.Escher96.obra.logic.dto.ObraDTO;
import co.edu.uniandes.csw.Escher96.obra.logic.api.IObraLogicService;
import co.edu.uniandes.csw.Escher96.obra.persistence.ObraPersistence;
import co.edu.uniandes.csw.Escher96.obra.persistence.api.IObraPersistence;
import co.edu.uniandes.csw.Escher96.obra.persistence.entity.ObraEntity;
import co.edu.uniandes.csw.Escher96.obra.persistence.converter.ObraConverter;
import static co.edu.uniandes.csw.Escher96.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ObraLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ObraLogicService.class.getPackage())
				.addPackage(IObraLogicService.class.getPackage())
				.addPackage(ObraPersistence.class.getPackage())
				.addPackage(ObraEntity.class.getPackage())
				.addPackage(IObraPersistence.class.getPackage())
                .addPackage(ObraDTO.class.getPackage())
                .addPackage(ObraConverter.class.getPackage())
                .addPackage(ObraEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IObraLogicService obraLogicService;
	
	@Inject
	private IObraPersistence obraPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<ObraDTO> dtos=obraPersistence.getObras();
		for(ObraDTO dto:dtos){
			obraPersistence.deleteObra(dto.getId());
		}
	}

	private List<ObraDTO> data=new ArrayList<ObraDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ObraDTO pdto=new ObraDTO();
			pdto.setUrlArchivo(generateRandom(String.class));
			pdto.setName(generateRandom(String.class));
			pdto=obraPersistence.createObra(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createObraTest(){
		ObraDTO ldto=new ObraDTO();
		ldto.setUrlArchivo(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		
		
		ObraDTO result=obraLogicService.createObra(ldto);
		
		Assert.assertNotNull(result);
		
		ObraDTO pdto=obraPersistence.getObra(result.getId());
		
		Assert.assertEquals(ldto.getUrlArchivo(), pdto.getUrlArchivo());	
		Assert.assertEquals(ldto.getName(), pdto.getName());	
	}
	
	@Test
	public void getObrasTest(){
		List<ObraDTO> list=obraLogicService.getObras();
		Assert.assertEquals(list.size(), data.size());
        for(ObraDTO ldto:list){
        	boolean found=false;
            for(ObraDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getObraTest(){
		ObraDTO pdto=data.get(0);
		ObraDTO ldto=obraLogicService.getObra(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getUrlArchivo(), ldto.getUrlArchivo());
		Assert.assertEquals(pdto.getName(), ldto.getName());
        
	}
	
	@Test
	public void deleteObraTest(){
		ObraDTO pdto=data.get(0);
		obraLogicService.deleteObra(pdto.getId());
        ObraDTO deleted=obraPersistence.getObra(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateObraTest(){
		ObraDTO pdto=data.get(0);
		
		ObraDTO ldto=new ObraDTO();
		ldto.setId(pdto.getId());
		ldto.setUrlArchivo(generateRandom(String.class));
		ldto.setName(generateRandom(String.class));
		
		
		obraLogicService.updateObra(ldto);
		
		
		ObraDTO resp=obraPersistence.getObra(pdto.getId());
		
		Assert.assertEquals(ldto.getUrlArchivo(), resp.getUrlArchivo());	
		Assert.assertEquals(ldto.getName(), resp.getName());	
	}
	
	@Test
	public void getObraPaginationTest(){
		
		ObraPageDTO dto1=obraLogicService.getObras(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		ObraPageDTO dto2=obraLogicService.getObras(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(ObraDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(ObraDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ObraDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ObraDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        ObraPageDTO dto3=obraLogicService.getObras(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(ObraDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(ObraDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}