/* ========================================================================
 * Copyright 2014 Escher96
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Escher96

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.Escher96.imagen.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.Escher96.imagen.logic.dto.ImagenPageDTO;
import co.edu.uniandes.csw.Escher96.imagen.logic.dto.ImagenDTO;
import co.edu.uniandes.csw.Escher96.imagen.persistence.api.IImagenPersistence;
import co.edu.uniandes.csw.Escher96.imagen.persistence.entity.ImagenEntity;
import co.edu.uniandes.csw.Escher96.imagen.persistence.converter.ImagenConverter;
import static co.edu.uniandes.csw.Escher96.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ImagenPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ImagenPersistence.class.getPackage())
				.addPackage(ImagenEntity.class.getPackage())
				.addPackage(IImagenPersistence.class.getPackage())
                .addPackage(ImagenDTO.class.getPackage())
                .addPackage(ImagenConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IImagenPersistence imagenPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ImagenEntity").executeUpdate();
	}

	private List<ImagenEntity> data=new ArrayList<ImagenEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ImagenEntity entity=new ImagenEntity();
			entity.setName(generateRandom(String.class));
			entity.setUrl(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createImagenTest(){
		ImagenDTO dto=new ImagenDTO();
		dto.setName(generateRandom(String.class));
		dto.setUrl(generateRandom(String.class));
		
		ImagenDTO result=imagenPersistence.createImagen(dto);
		
		Assert.assertNotNull(result);
		
		ImagenEntity entity=em.find(ImagenEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getUrl(), entity.getUrl());
	}
	
	@Test
	public void getImagensTest(){
		List<ImagenDTO> list=imagenPersistence.getImagens();
		Assert.assertEquals(list.size(), data.size());
        for(ImagenDTO dto:list){
        	boolean found=false;
            for(ImagenEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getImagenTest(){
		ImagenEntity entity=data.get(0);
		ImagenDTO dto=imagenPersistence.getImagen(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getUrl(), dto.getUrl());
        
	}
	
	@Test
	public void deleteImagenTest(){
		ImagenEntity entity=data.get(0);
		imagenPersistence.deleteImagen(entity.getId());
        ImagenEntity deleted=em.find(ImagenEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateImagenTest(){
		ImagenEntity entity=data.get(0);
		
		ImagenDTO dto=new ImagenDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setUrl(generateRandom(String.class));
		
		
		imagenPersistence.updateImagen(dto);
		
		
		ImagenEntity resp=em.find(ImagenEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getUrl(), resp.getUrl());	
	}
	
	@Test
	public void getImagenPaginationTest(){
		//Page 1
		ImagenPageDTO dto1=imagenPersistence.getImagens(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ImagenPageDTO dto2=imagenPersistence.getImagens(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ImagenDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ImagenEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ImagenDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ImagenEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}