/* ========================================================================
 * Copyright 2014 Escher96
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Escher96

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.Escher96.trabajo.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.Escher96.trabajo.logic.dto.TrabajoPageDTO;
import co.edu.uniandes.csw.Escher96.trabajo.logic.dto.TrabajoDTO;
import co.edu.uniandes.csw.Escher96.trabajo.persistence.api.ITrabajoPersistence;
import co.edu.uniandes.csw.Escher96.trabajo.persistence.entity.TrabajoEntity;
import co.edu.uniandes.csw.Escher96.trabajo.persistence.converter.TrabajoConverter;
import static co.edu.uniandes.csw.Escher96.util._TestUtil.*;

@RunWith(Arquillian.class)
public class TrabajoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(TrabajoPersistence.class.getPackage())
				.addPackage(TrabajoEntity.class.getPackage())
				.addPackage(ITrabajoPersistence.class.getPackage())
                .addPackage(TrabajoDTO.class.getPackage())
                .addPackage(TrabajoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ITrabajoPersistence trabajoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from TrabajoEntity").executeUpdate();
	}

	private List<TrabajoEntity> data=new ArrayList<TrabajoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			TrabajoEntity entity=new TrabajoEntity();
			entity.setResenha(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createTrabajoTest(){
		TrabajoDTO dto=new TrabajoDTO();
		dto.setResenha(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		TrabajoDTO result=trabajoPersistence.createTrabajo(dto);
		
		Assert.assertNotNull(result);
		
		TrabajoEntity entity=em.find(TrabajoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getResenha(), entity.getResenha());
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getTrabajosTest(){
		List<TrabajoDTO> list=trabajoPersistence.getTrabajos();
		Assert.assertEquals(list.size(), data.size());
        for(TrabajoDTO dto:list){
        	boolean found=false;
            for(TrabajoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getTrabajoTest(){
		TrabajoEntity entity=data.get(0);
		TrabajoDTO dto=trabajoPersistence.getTrabajo(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getResenha(), dto.getResenha());
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteTrabajoTest(){
		TrabajoEntity entity=data.get(0);
		trabajoPersistence.deleteTrabajo(entity.getId());
        TrabajoEntity deleted=em.find(TrabajoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateTrabajoTest(){
		TrabajoEntity entity=data.get(0);
		
		TrabajoDTO dto=new TrabajoDTO();
		dto.setId(entity.getId());
		dto.setResenha(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		
		trabajoPersistence.updateTrabajo(dto);
		
		
		TrabajoEntity resp=em.find(TrabajoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getResenha(), resp.getResenha());	
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
	
	@Test
	public void getTrabajoPaginationTest(){
		//Page 1
		TrabajoPageDTO dto1=trabajoPersistence.getTrabajos(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        TrabajoPageDTO dto2=trabajoPersistence.getTrabajos(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(TrabajoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(TrabajoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(TrabajoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(TrabajoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}