/* ========================================================================
 * Copyright 2014 Escher96
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Escher96

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.Escher96.obra.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.Escher96.obra.logic.dto.ObraPageDTO;
import co.edu.uniandes.csw.Escher96.obra.logic.dto.ObraDTO;
import co.edu.uniandes.csw.Escher96.obra.persistence.api.IObraPersistence;
import co.edu.uniandes.csw.Escher96.obra.persistence.entity.ObraEntity;
import co.edu.uniandes.csw.Escher96.obra.persistence.converter.ObraConverter;
import static co.edu.uniandes.csw.Escher96.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ObraPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ObraPersistence.class.getPackage())
				.addPackage(ObraEntity.class.getPackage())
				.addPackage(IObraPersistence.class.getPackage())
                .addPackage(ObraDTO.class.getPackage())
                .addPackage(ObraConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IObraPersistence obraPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ObraEntity").executeUpdate();
	}

	private List<ObraEntity> data=new ArrayList<ObraEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ObraEntity entity=new ObraEntity();
			entity.setUrlArchivo(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createObraTest(){
		ObraDTO dto=new ObraDTO();
		dto.setUrlArchivo(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		ObraDTO result=obraPersistence.createObra(dto);
		
		Assert.assertNotNull(result);
		
		ObraEntity entity=em.find(ObraEntity.class, result.getId());
		
		Assert.assertEquals(dto.getUrlArchivo(), entity.getUrlArchivo());
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getObrasTest(){
		List<ObraDTO> list=obraPersistence.getObras();
		Assert.assertEquals(list.size(), data.size());
        for(ObraDTO dto:list){
        	boolean found=false;
            for(ObraEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getObraTest(){
		ObraEntity entity=data.get(0);
		ObraDTO dto=obraPersistence.getObra(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getUrlArchivo(), dto.getUrlArchivo());
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteObraTest(){
		ObraEntity entity=data.get(0);
		obraPersistence.deleteObra(entity.getId());
        ObraEntity deleted=em.find(ObraEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateObraTest(){
		ObraEntity entity=data.get(0);
		
		ObraDTO dto=new ObraDTO();
		dto.setId(entity.getId());
		dto.setUrlArchivo(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		
		obraPersistence.updateObra(dto);
		
		
		ObraEntity resp=em.find(ObraEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getUrlArchivo(), resp.getUrlArchivo());	
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
	
	@Test
	public void getObraPaginationTest(){
		//Page 1
		ObraPageDTO dto1=obraPersistence.getObras(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ObraPageDTO dto2=obraPersistence.getObras(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ObraDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ObraEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ObraDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ObraEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}