/* ========================================================================
 * Copyright 2014 Escher96
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 Escher96

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.Escher96.video.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.Escher96.video.logic.dto.VideoPageDTO;
import co.edu.uniandes.csw.Escher96.video.logic.dto.VideoDTO;
import co.edu.uniandes.csw.Escher96.video.persistence.api.IVideoPersistence;
import co.edu.uniandes.csw.Escher96.video.persistence.entity.VideoEntity;
import co.edu.uniandes.csw.Escher96.video.persistence.converter.VideoConverter;
import static co.edu.uniandes.csw.Escher96.util._TestUtil.*;

@RunWith(Arquillian.class)
public class VideoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(VideoPersistence.class.getPackage())
				.addPackage(VideoEntity.class.getPackage())
				.addPackage(IVideoPersistence.class.getPackage())
                .addPackage(VideoDTO.class.getPackage())
                .addPackage(VideoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IVideoPersistence videoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from VideoEntity").executeUpdate();
	}

	private List<VideoEntity> data=new ArrayList<VideoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			VideoEntity entity=new VideoEntity();
			entity.setUrlArchivo(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createVideoTest(){
		VideoDTO dto=new VideoDTO();
		dto.setUrlArchivo(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		VideoDTO result=videoPersistence.createVideo(dto);
		
		Assert.assertNotNull(result);
		
		VideoEntity entity=em.find(VideoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getUrlArchivo(), entity.getUrlArchivo());
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getVideosTest(){
		List<VideoDTO> list=videoPersistence.getVideos();
		Assert.assertEquals(list.size(), data.size());
        for(VideoDTO dto:list){
        	boolean found=false;
            for(VideoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getVideoTest(){
		VideoEntity entity=data.get(0);
		VideoDTO dto=videoPersistence.getVideo(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getUrlArchivo(), dto.getUrlArchivo());
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteVideoTest(){
		VideoEntity entity=data.get(0);
		videoPersistence.deleteVideo(entity.getId());
        VideoEntity deleted=em.find(VideoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateVideoTest(){
		VideoEntity entity=data.get(0);
		
		VideoDTO dto=new VideoDTO();
		dto.setId(entity.getId());
		dto.setUrlArchivo(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		
		videoPersistence.updateVideo(dto);
		
		
		VideoEntity resp=em.find(VideoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getUrlArchivo(), resp.getUrlArchivo());	
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
	
	@Test
	public void getVideoPaginationTest(){
		//Page 1
		VideoPageDTO dto1=videoPersistence.getVideos(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        VideoPageDTO dto2=videoPersistence.getVideos(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(VideoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(VideoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(VideoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(VideoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}